### ISSUE TITLE
Not able to find Shimmer3 device

### ISSUE THREAD

**Issue by maneetgoyal** [ShimmerResearch/shimmer3#14]
Hi all,

I am trying to connect to Shimmer3 device via Serial Port. Use the following 2 alternates:

- https://serialport.io/docs/bin-list
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API

The device can be located on Win10 in the Bluetooth menu as `Shimmer3-XXXX`. But when scanning via the above 2 methods, the device list doesn't show the Shimmer3 device.

How can I connect to Shimmer3 programmatically using JavaScript?

**Comment by maneetgoyal** [comment]
Related issue: https://github.com/ShimmerEngineering/ConsensysGRPCAPI/issues/1

**Comment by maneetgoyal** [comment]
@jongchern Requesting for help, in case you can spot any issue.

_I'm with RAMROD XR GmBH_

**Comment by JongChern** [comment]
hi, @maneetgoyal this is not an appropriate place to create an issue, can you please contact support and address it to me. we normally dont help custom apis but i`ll try to help where possible.

**Comment by maneetgoyal** [comment]
Thanks for the reply, have contacted info@shimmersensing.com and asked them to include you in the email trail
