### ISSUE TITLE
macros.h file inquiry

### ISSUE THREAD

**Issue by mattsonny** [ShimmerResearch/shimmer3#2]
Greetings friends,

My name is Matt and I am currently an undergraduate student at NCSU working on a wearable tech Senior Design project. As part of the project I need to use a RN42 Bluetooth chip with an MSP430 to receive commands.

Your code repository: 
[https://github.com/ShimmerResearch/shimmer3/tree/master/BtStream/Bluetooth](https://github.com/ShimmerResearch/shimmer3/tree/master/BtStream/Bluetooth) 

has been very helpful to this end. However it is missing the **macros.h** file associated with it and I am struggling to adapt the code to my project without it. 

Is there anyway that his file may be added to the repository?This would immensely help me with my project.

I wish you success and riches,
-Matt

**Comment by SJFOM** [comment]
Hi Matt,

Thanks for your query, happy to hear the repository is helping you with your project.

We typically don't offer support for non-Shimmer related products/projects. However, in reference to a "macros.h" file - we don't have/use any file by that name. The repository contains all the files necessary to operate the Shimmer3 device with its RN42 Bluetooth module, we have not omitted any files.

Best wishes for your project.

Sam

Shimmer

**Comment by ShimmerEngineering** [comment]
Matt,

Please note the copyright notice within the source code files.
Shimmers source code may not be used be used commercially except when used with a Shimmer product.

Please provide details of the project you are working on so that Shimmer can confirm the project is non-commercial.

Norman Davidson
