### ISSUE TITLE
Regarding GSR and PPG with Python

### ISSUE THREAD

**Issue by arsiboo** [ShimmerResearch/shimmer3#4]
Hi,

I recently started working with Shimmer Sensor, and I have downloaded the following python codes, run it through CMD in order to access information while Shimmer Sensor is on. So far I managed to get some information such as accX, accY, accZ. however my goal is to get GSR+ information which divides into two parts GSR and PPG, but I'm unable to find them in the codes, I have so far found two files containing only UART_COMP_GSR=0x05, however, I'm unable to get GSR and PPG data during the runtime when I run the python codes on CMD. 

Now I would like to know if this information is reachable through these python codes? if so which file I need to take into consideration?

**Comment by nomahony** [comment]
We should get the SN/BT number and age of unit from him first if possible,

 

Rgds…..Paddy.
