### ISSUE TITLE
Analog to Digital Conversion

### ISSUE THREAD

**Issue by akaniklaus** [ShimmerResearch/shimmer3#5]
Dear Sir/Madam,

We managed to successfully run aAccel5Hz example but that's reading 16-bit raw analog sensor data from the device. We don't know how to convert this to m/s^2 digital values that we are already using by exporting from the software. (We assume that post-processing and calibration might be necessary). We couldn't find any in-depth resource about that process online. We would welcome and greatly appreciate if you can advice about that as soon as possible.

Sincerely,

**Comment by SJFOM** [comment]
Hi there,

Thanks for reaching out with your query. For technical support purposes, I would please ask that you send this query to our [technical support system](http://www.shimmersensing.com/support/wearable-sensing-support/) so we may track it accordingly. One of our engineers will reply with an answer promptly.

Kind Regards,

Shimmer Engineering Team

**Comment by akaniklaus** [comment]
Dear Sam,

I have just asked my colleagues to create a support ticket as I am unfamiliar myself with those details as a new employee (such as where did they purchase from). Have a nice day.

Sincerely,
Kamer
