### ISSUE TITLE
Race Condition in Shimmer3 Bluetooth Stack

### ISSUE THREAD

**Issue by lumagi** [ShimmerResearch/shimmer3#7]
I work with Shimmer3 devices under Linux and interface directly with them via the serial Bluetooth interface. I noticed that there appears to be some kind of race condition that occurs when the Bluetooth interface sends responses to Bluetooth commands while streaming data.

For me, this issue specifically occurs when I stream data from the device to the host and try to stop this stream with the STOP_STREAMING_COMMAND. The command is successfully received by the Shimmer but the acknowledgment 0xFF is sometimes lost and not transmitted to the host, which throws of my state machine on the host side. I believe that the reason for this is the initial conditional check in the `BT_write` routine ([LogAndStream/shimmer3_common_source/Bluetooth_SD/RN42.c:750](https://github.com/ShimmerResearch/shimmer3/blob/04d8e21e21c4be8b58596cfc57d9eb5f5f7d68c5/LogAndStream/shimmer3_common_source/Bluetooth_SD/RN42.c#L750)) which returns immediately if another transmission is still in progress.

I was able to successfully recreate the bug using the following steps. I used Wireshark to dissect the Bluetooth data stream between Shimmer and Host.
* Set the baud_rate config parameter for communication between main CPU and Bluetooth to the lowest possible value (1)
* Configure the Shimmer to stream data. Here it was sufficient to send a single 16bit channel, i.e. a total of 6 bytes for the DataPacket
* Send the START_STREAMING_COMMAND, wait for several seconds and then send the STOP_STREAMING_COMMAND
* The acknowledgment byte 0xFF will likely not appear in the stream response

**Comment by lumagi** [comment]
My first idea was to instead use the [BT_append](https://github.com/ShimmerResearch/shimmer3/blob/04d8e21e21c4be8b58596cfc57d9eb5f5f7d68c5/LogAndStream/shimmer3_common_source/Bluetooth_SD/RN42.c#L779) function. However, the memcpy operation always caused a partial overwrite of the existing data in the buffer, and I was unable to fully diagnose the issue without a JTAG adapter.

**Comment by marknolan** [comment]
@lumagi We were aware of this issue but we haven't been able to get around to fixing it. To ignore the issue in Consensys, we just send the stop streaming command and assume that it has been successfully received. 

Is this a critical bug for your application or could you work around it somehow for the time being?

**Comment by lumagi** [comment]
Since I was previously unable to fix the `BT_append` method, I applied a workaround where the device busy waits for the send buffer to empty out and then queues the new bytes. Since the bug only occurs with the single `STOP_STREAMING` acknowledgment, it does not lead to an issue with the main loop of the device.
However, since opening the issue here on GitHub, I took another look at the `BT_append` method and was able to fix the bugs in it such that the append now works correctly. Please take a look at pull request #12.

**Comment by marknolan** [comment]
As described in #12 we've hopefully solved this issue by switching to a FIFO for Bluetooth data transmission.
